version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME:  /py-app/docker_user
    DOCKER_PASSWORD: /py-app/docker_password
    DOCKER_REGISTRY: /py-app/docker_url

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "In build phase"
      # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
      - docker build -t "$DOCKER_REGISTRY/$DOCKER_USERNAME/py-app:$IMAGE_TAG" .
      - docker push "$DOCKER_REGISTRY/$DOCKER_USERNAME/py-app:$IMAGE_TAG"
  post_build:
    commands:
      - echo "Build is completed and image is pushed to ECR."